aws-vm ansible_host=100.53.34.160 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mainec2.pem
azure-vm ansible_host=20.127.44.243 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa
